"""
Saves each digest run as a markdown file in digests/YYYY/MM/
So the repo becomes a searchable archive of every brief ever sent.

File naming:
  digests/2026/04/2026-04-04_0600_daily.md
  digests/2026/04/2026-04-06_1800_weekly.md
"""
from datetime import datetime
from pathlib import Path
from typing import Dict, Any


DIGESTS_DIR = Path(__file__).parent.parent / "digests"


def save_digest(digest: Dict[str, Any], digest_type: str, item_count: int) -> Path:
    """Write digest to markdown file. Returns the path written."""
    now = datetime.utcnow()
    out_dir = DIGESTS_DIR / now.strftime("%Y") / now.strftime("%m")
    out_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{now.strftime('%Y-%m-%d_%H%M')}_{digest_type}.md"
    out_path = out_dir / filename

    md = _render_markdown(digest, digest_type, item_count, now)
    out_path.write_text(md, encoding="utf-8")
    print(f"[output] Saved digest to {out_path}")
    return out_path


def _render_markdown(digest: Dict[str, Any], digest_type: str, item_count: int, now: datetime) -> str:
    if digest_type == "weekly":
        title = f"Weekly Intelligence Summary — {now.strftime('%B %d, %Y')}"
    elif now.hour < 12:
        title = f"Morning Intelligence Brief — {now.strftime('%A, %B %d, %Y')}"
    else:
        title = f"Evening Intelligence Recap — {now.strftime('%A, %B %d, %Y')}"

    lines = [
        f"# {title}",
        f"",
        f"**Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Type:** {digest_type}  ",
        f"**Signals analyzed:** {item_count}  ",
        f"",
        f"---",
        f"",
        f"## Executive Brief",
        f"",
        digest.get("executive_brief", "_No summary available._"),
        f"",
    ]

    # Market Pulse
    mp = digest.get("market_pulse", {})
    if mp:
        lines += [
            f"---",
            f"",
            f"## 📈 Market Pulse  `{mp.get('severity', 'INFO')}`",
            f"",
            mp.get("summary", ""),
            f"",
        ]
        movers = mp.get("top_movers") or mp.get("notable_moves", [])
        if movers:
            for item in movers:
                lines.append(f"- {item}")
            lines.append("")
        if mp.get("outlook"):
            lines += [f"> **Outlook:** {mp['outlook']}", ""]

    # Geopolitical
    geo = digest.get("geopolitical_watch", {})
    if geo:
        lines += [
            f"---",
            f"",
            f"## 🌍 Geopolitical Watch  `{geo.get('severity', 'INFO')}`",
            f"",
            geo.get("summary", ""),
            f"",
        ]
        events = geo.get("key_events") or geo.get("key_developments", [])
        for item in events:
            lines.append(f"- {item}")
        if events:
            lines.append("")
        risks = geo.get("escalation_risks", [])
        if risks:
            lines += ["**Escalation Watch:**", ""]
            for r in risks:
                lines.append(f"- ⚠️ {r}")
            lines.append("")

    # Cyber
    cyber = digest.get("cyber_threat_board", {})
    if cyber:
        lines += [
            f"---",
            f"",
            f"## 🛡️ Cyber Threat Board  `{cyber.get('severity', 'INFO')}`",
            f"",
            cyber.get("summary", ""),
            f"",
        ]
        threats = cyber.get("top_threats") or cyber.get("top_vulnerabilities", [])
        for item in threats:
            lines.append(f"- {item}")
        if threats:
            lines.append("")
        if cyber.get("threat_actor_activity"):
            lines += [f"_{cyber['threat_actor_activity']}_", ""]

    # Social
    social = digest.get("social_signals", {})
    if social:
        lines += [
            f"---",
            f"",
            f"## 📡 Social Signals  `{social.get('severity', 'INFO')}`",
            f"",
            social.get("summary", ""),
            f"",
        ]
        for item in social.get("trending_topics", []):
            lines.append(f"- {item}")
        lines.append("")

    # Weekly extras
    watchlist = digest.get("next_week_watchlist", [])
    if watchlist:
        lines += [
            f"---",
            f"",
            f"## 🔭 Next Week Watchlist",
            f"",
        ]
        for item in watchlist:
            lines.append(f"- {item}")
        lines.append("")

    # Confidence note
    if digest.get("confidence_note"):
        lines += [
            f"---",
            f"",
            f"> ⚠️ **Note:** {digest['confidence_note']}",
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"_Generated by [daily-intel](https://github.com/jeffwatson/daily-intel) · Claude Haiku · {item_count} signals_",
    ]

    return "\n".join(lines)
